// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYmwVO0xlLR9BouHRR6BP631ElHdUv24E',
    appId: '1:135236436314:web:d3be27ffa374ed308bf363',
    messagingSenderId: '135236436314',
    projectId: 'cloud-cafe-12ee3',
    authDomain: 'cloud-cafe-12ee3.firebaseapp.com',
    storageBucket: 'cloud-cafe-12ee3.appspot.com',
    measurementId: 'G-XE19LQ133Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU22D7JH1GbdHYRrQm7uvD_R6gZKw3Tgw',
    appId: '1:135236436314:android:9d8e9df91ac2968d8bf363',
    messagingSenderId: '135236436314',
    projectId: 'cloud-cafe-12ee3',
    storageBucket: 'cloud-cafe-12ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqlyNQjfJSOuGhPLKK4r8JXQ4biKKadM',
    appId: '1:135236436314:ios:593104b23fae71f48bf363',
    messagingSenderId: '135236436314',
    projectId: 'cloud-cafe-12ee3',
    storageBucket: 'cloud-cafe-12ee3.appspot.com',
    iosBundleId: 'com.example.cloudCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqlyNQjfJSOuGhPLKK4r8JXQ4biKKadM',
    appId: '1:135236436314:ios:51459bc9c93cb8a88bf363',
    messagingSenderId: '135236436314',
    projectId: 'cloud-cafe-12ee3',
    storageBucket: 'cloud-cafe-12ee3.appspot.com',
    iosBundleId: 'com.example.cloudCafe.RunnerTests',
  );
}
